name: FastShop CI

on:
  push:
    branches: [ "main", "develop", "feature/**" ] # Aciona o workflow em push para essas branches
  pull_request:
    branches: [ "main", "develop" ] # Aciona o workflow em PRs para essas branches

jobs:
  build-and-deploy: # Renomeei o job para refletir que agora ele também faz deploy (push)
    runs-on: ubuntu-latest # O sistema operacional da máquina virtual onde o job será executado

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4 # Baixa o código do seu repositório

      - name: Configurar Java 21
        uses: actions/setup-java@v4 # Configura o ambiente Java 21
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven' # Configura o cache do Maven para builds mais rápidos

      - name: Construir e Testar com Maven # Compila o código, roda os testes e gera o JAR
        run: mvn -B package --file pom.xml

      - name: Exibir Log de Testes # Opcional: Mostra um resumo dos resultados dos testes
        run: cat target/surefire-reports/TEST-*.xml || true

      - name: Configurar Docker Buildx # Configura o Buildx para builds Docker eficientes
        uses: docker/setup-buildx-action@v3

      # NOVO PASSO: Login no Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v3 # Ação para fazer login no Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Usa o Secret para o username
          password: ${{ secrets.DOCKERHUB_TOKEN }}   # Usa o Secret para o token

      # NOVO PASSO: Construir e Fazer Push da Imagem Docker
      - name: Construir e Fazer Push da Imagem Docker
        uses: docker/build-push-action@v5 # Ação para construir e enviar a imagem
        with:
          context: . # O diretório do Dockerfile (raiz do projeto)
          file: ./Dockerfile # Caminho para o seu Dockerfile
          # Tags para a imagem: uma com 'latest' e outra com o hash do commit
          tags: albertovilar/fastshop-backend:latest, albertovilar/fastshop-backend:${{ github.sha }}
          push: true # Habilita o push para o Docker Hub